---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: food-master
    namespace: jaan
    labels:
      app: food-master
spec:
 replicas: 3
 selector:
     matchLabels:
      app: food-master
 template:
     metadata:
        labels:
            app: food-master
     spec:
       containers:
         - name: food-master
           image:156739282338.dkr.ecr.ap-south-1.amazonaws.com/test1:latest
           imagePullPolicy: "Always"
           ports:
           - containerPort: 80
