---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: food-master
    namespace: jaan
    labels:
      app: food
spec:
 replicas: 3
 selector:
     matchLabels:
      app: food
 template:
     metadata:
        labels:
            app: food
     spec:
       containers:
         - name: food
           image: docker push 156739282338.dkr.ecr.ap-south-1.amazonaws.com/test1:latest
           imagePullPolicy: "Always"
           ports:
           - containerPort: 80
